### ISSUE TITLE
Key file readable for anyone

### ISSUE THREAD

**Issue by mastodon** [saltstack-formulas/openvpn-formula#27]
The state deploys world-readable keys.
 ```config.sls``` should be updated as follows:

```
{% if config.key is defined and config.key_content is defined %}
# Deploy {{ type }} {{ name }} private key file
openvpn_config_{{ type }}_{{ name }}_key_file:
  file.managed:
    - name: {{ config.key }}
    - contents_pillar: openvpn:{{ type }}:{{ name }}:key_content
    - mode: '660'
    - makedirs: True
    - watch_in:
      - service: openvpn_service
{% endif %}
```
