### ISSUE TITLE
Empty config

### ISSUE THREAD

**Issue by deadlyhawk** [saltstack-formulas/openvpn-formula#89]
Hello

on debian strech and saltstack 2018.3.2+ds-1 generate empty config

```
# OpenVPN server configuration 'xxxx'
# Managed by Salt
# Template: salt://openvpn/files/server.jinja


; Networking
proto udp


; Operating system
dev tun
user nobody
group nogroup
persist-key
persist-tun


; Data transfer


; Logging / Debugging
verb 3


; Cryptographic parameters
# ca is not set !
# cert is not set !
# key is not set !

; check with https://bettercrypto.org/static/applied-crypto-hardening.pdf

; Certificate verification
; (Anti MITM)


; Up/Down Scripts


tls-server
port 1194
```

i must remove in file `openvpn/config.sls` on line 37 ([this](https://github.com/saltstack-formulas/openvpn-formula/blob/master/openvpn/config.sls#L37)) json_encode_dict  and now config for server is generate OK.

```yaml
config:
`openvpn:
  lookup:
    dh_files: ['4096']
  server:
    name:
      port: 1194
      proto: udp
      topology: subnet
      ca: /etc/openvpn/ca.crt
      ca_content: |
        -----BEGIN CERTIFICATE-----
        -----END CERTIFICATE-----
      cert: /etc/openvpn/cert.pem
      cert_content: |
        -----BEGIN CERTIFICATE-----
        -----END CERTIFICATE-----
      key: /etc/openvpn/key.pem
      key_content: |
        -----BEGIN PRIVATE KEY-----
        -----END PRIVATE KEY-----
      dh: dh4096.pem
      server: 'x.0.0.0 255.255.255.0'
      ifconfig_pool_persist: ipp.txt
      push:
        - "route x.0.0.0 255.255.255.0"
      client_config:
        xxxxx: |
          ifconfig-push x.0.0.x 255.255.255.0
      client_to_client: False
      tls_auth: /etc/openvpn/tls.key 0
      tls_crypt: /etc/openvpn/tls.key
      tls_version_min: 1.2
      ta_content: |
        -----BEGIN OpenVPN Static key V1-----
        -----END OpenVPN Static key V1-----
      comp_lzo:
      user: nobody
      group: nogroup
      persist_key:
      persist_tun:
      status: /var/log/openvpn/openvpn-status.log
      log: /var/log/openvpn/openvpn.log
      client_config_dir: clients
`
```
